version: "3.7"

# #################################################################
# #                            SERVICES                           #
# #################################################################
services:
  # =========================
  # =        TRAEFIK        =
  # =========================
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--providers.file.directory=/conf"
      - "--providers.file.watch=true"
      - "--providers.docker=true"
      - "--providers.docker.defaultRule="
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le-tls.acme.tlsChallenge=true"
      - "--certificatesresolvers.le-tls.acme.email=${ADMIN_MAIL}"
      - "--certificatesresolvers.le-tls.acme.storage=/letsencrypt/acme.json"
      - "--api=true"
      - "--ping.manualrouting=true"
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik
    volumes:
      - ./conf/traefik:/conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-cert:/letsencrypt/
    environment:
      - "TZ=${DEFAULT_TIMEZONE}"

  # =========================
  # =     AUTO-UPDATER      =
  # =========================
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    command: --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "TZ=${DEFAULT_TIMEZONE}"

  # =========================
  # =  KINKY HARBOR: DEMO   =
  # =========================
  kh-demo-frontend:
    image: kinkyharbor/kinkyharbor-frontend-nuxt:latest
    container_name: kh-demo-frontend
    restart: always
    networks:
      - traefik
    environment:
      - "TZ=${DEFAULT_TIMEZONE}"
      - "NUXT_HOST=0.0.0.0"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

  kh-demo-backend:
    image: kinkyharbor/kinkyharbor-backend-drf:latest
    container_name: kh-demo-backend
    restart: always
    networks:
      - traefik
    environment:
      - "TZ=${DEFAULT_TIMEZONE}"
      - "DEMO=True"
      - "FRONTEND_URL=https://demo.${DEFAULT_DOMAIN}"
      - "SECRET_KEY=${KH_DEMO_SECRET_KEY}"
      - "ALLOWED_HOSTS=https://demo-api.${DEFAULT_DOMAIN}"
      - "CORS=https://demo.${DEFAULT_DOMAIN}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

  # =========================
  # =      MAINTENANCE      =
  # =========================
  maintenance:
    image: everydayhero/maintenance:latest
    container_name: maintenance
    restart: always
    networks:
      - traefik
    volumes:
      - "./conf/maintenance:/usr/share/nginx/html"
    environment:
      - "TZ=${DEFAULT_TIMEZONE}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

# #################################################################
# #                            VOLUMES                            #
# #################################################################
volumes:
  traefik-cert:

# #################################################################
# #                            NETWORKS                           #
# #################################################################
networks:
  traefik:
    name: traefik
