version: "3.7"

# #################################################################
# #                            SERVICES                           #
# #################################################################
services:
  # =========================
  # =        TRAEFIK        =
  # =========================
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--providers.file.directory=/conf"
      - "--providers.file.watch=true"
      - "--providers.docker=true"
      - "--providers.docker.defaultRule="
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le-tls.acme.tlsChallenge=true"
      - "--certificatesresolvers.le-tls.acme.email=${ADMIN_MAIL}"
      - "--certificatesresolvers.le-tls.acme.storage=/letsencrypt/acme.json"
      - "--api=true"
      - "--ping.manualrouting=true"
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik
    volumes:
      - ./conf/traefik:/conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-cert:/letsencrypt/
    environment:
      - "TZ=${DEFAULT_TIMEZONE}"

  # =========================
  # =     AUTO-UPDATER      =
  # =========================
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    command: --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "TZ=${DEFAULT_TIMEZONE}"

  # =========================
  # =  KINKY HARBOR: DEMO   =
  # =========================
  kh-demo-frontend:
    image: kinkyharbor/kinkyharbor-frontend-nuxt:latest
    container_name: kh-demo-frontend
    restart: always
    networks:
      - traefik
    environment:
      - "TZ=${DEFAULT_TIMEZONE}"
      - "NUXT_HOST=0.0.0.0"
      - "API_URL=https://demo-api.${DEFAULT_DOMAIN}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

  kh-demo-backend:
    image: kinkyharbor/kinkyharbor-backend-fastapi:latest
    container_name: kh-demo-backend
    restart: always
    depends_on:
      - hk-demo-mongo
    networks:
      - traefik
      - kh-backend
    environment:
      - "TZ=${DEFAULT_TIMEZONE}"
      - "FRONTEND_URL=https://demo.${DEFAULT_DOMAIN}"
      - "CORS=https://demo.${DEFAULT_DOMAIN};https://demo.${DOMAIN_BE};https://demo.${DOMAIN_NL}"
      - "EMAIL_FROM_ADDRESS=no-reply@${DEFAULT_DOMAIN}"
      - "EMAIL_HOSTNAME=${MAIL_HOST}"
      - "EMAIL_PORT=${MAIL_PORT}"
      - "EMAIL_USERNAME=${MAIL_USER}"
      - "EMAIL_PASSWORD=${MAIL_PASS}"
      - "MONGO_HOST=kh-demo-mongo"
    volumes:
      - "./conf/kh-demo/jwt-keys:/jwt-keys"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

  hk-demo-mongo:
    image: mongo
    container_name: kh-demo-mongo
    restart: always
    networks:
      - kh-backend
    environment:
      - "TZ=${DEFAULT_TIMEZONE}"

  # =========================
  # =      MAINTENANCE      =
  # =========================
  maintenance:
    image: everydayhero/maintenance:latest
    container_name: maintenance
    restart: always
    networks:
      - traefik
    volumes:
      - "./conf/maintenance:/usr/share/nginx/html"
    environment:
      - "TZ=${DEFAULT_TIMEZONE}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

# #################################################################
# #                            VOLUMES                            #
# #################################################################
volumes:
  traefik-cert:

# #################################################################
# #                            NETWORKS                           #
# #################################################################
networks:
  traefik:
    name: traefik

  kh-backend:
    name: kh-backend
