version: "3.7"

# #################################################################
# #                            SERVICES                           #
# #################################################################
services:
  # =========================
  # =        TRAEFIK        =
  # =========================
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--providers.file.directory=/conf"
      - "--providers.file.watch=true"
      - "--providers.docker=true"
      - "--providers.docker.defaultRule="
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le-tls.acme.tlsChallenge=true"
      - "--certificatesresolvers.le-tls.acme.email=${ADMIN_MAIL}"
      - "--certificatesresolvers.le-tls.acme.storage=/letsencrypt/acme.json"
      - "--api=true"
      - "--ping.manualrouting=true"
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik
    volumes:
      - ./conf/traefik:/conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-cert:/letsencrypt/
    environment:
      - "TZ=${DEFAULT_TIMEZONE}"

  # =========================
  # =     AUTO-UPDATER      =
  # =========================
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    command: --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "TZ=${DEFAULT_TIMEZONE}"

  # =========================
  # =  KINKY HARBOR: TEST   =
  # =========================
  kh-test-frontend:
    image: kinkyharbor/kinkyharbor-frontend-nuxt:precompiled-test
    container_name: kh-test-frontend
    restart: always
    networks:
      - traefik
    environment:
      - "TZ=${DEFAULT_TIMEZONE}"
      - "DEMO=True"
      - "KH_BASE_URL=https://test.${DEFAULT_DOMAIN}"
      - "API_URL=https://test-api.${DEFAULT_DOMAIN}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

  kh-test-backend:
    image: kinkyharbor/kinkyharbor-backend-fastapi:latest
    container_name: kh-test-backend
    restart: always
    depends_on:
      - kh-test-mongo
    networks:
      - traefik
      - kh-test-backend
    environment:
      - "DEBUG=True"
      - "TZ=${DEFAULT_TIMEZONE}"
      - "FRONTEND_URL=https://test.${DEFAULT_DOMAIN}"
      - "CORS=[\"https://test.${DEFAULT_DOMAIN}\"]"
      - "EMAIL_HOSTNAME=${MAIL_HOST}"
      - "EMAIL_PORT=${MAIL_PORT}"
      - "EMAIL_USERNAME=${MAIL_USER}"
      - "EMAIL_PASSWORD=${MAIL_PASS}"
      - "MONGO_HOST=kh-test-mongo"
      - "CELERY_RABBITMQ_HOST=kh-test-rabbitmq"
    volumes:
      - "./conf/kh-test/jwt-keys:/app/jwt-keys"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

  kh-test-mongo:
    image: mongo
    container_name: kh-test-mongo
    restart: always
    networks:
      - kh-test-backend
    environment:
      - "TZ=${DEFAULT_TIMEZONE}"

  kh-test-mongo-web:
    container_name: kh-test-mongo-express
    image: mongo-express
    environment:
      - "ME_CONFIG_BASICAUTH_USERNAME=${KH_TEST_MONGO_USER}"
      - "ME_CONFIG_BASICAUTH_PASSWORD=${KH_TEST_MONGO_PASS}"
      - "ME_CONFIG_MONGODB_SERVER=kh-test-mongo"
      - "TZ=${DEFAULT_TIMEZONE}"
    depends_on:
      - kh-test-mongo
    networks:
      - kh-test-backend
      - traefik

  kh-test-rabbitmq:
    container_name: kh-test-rabbitmq
    image: rabbitmq:3-management
    networks:
      - kh-test-backend

  kh-test-flower:
    container_name: kh-test-flower
    image: mher/flower
    environment:
      - "FLOWER_BASIC_AUTH=${KH_TEST_FLOWER_USER}:${KH_TEST_FLOWER_PASS}"
      - "TZ=${DEFAULT_TIMEZONE}"
    command:
      - "--broker=amqp://guest@harbor-rabbitmq:5672//"
      - "--broker_api=http://guest:guest@harbor-rabbitmq:15672/api/"
    depends_on:
      - kh-test-rabbitmq
    networks:
      - kh-test-backend
      - traefik

  kh-test-scheduler:
    image: kinkyharbor/kinkyharbor-backend-scheduler:latest
    container_name: kh-test-scheduler
    networks:
      - kh-test-backend
    environment:
      - "CELERY_RABBITMQ_HOST=kh-test-rabbitmq"
    depends_on:
      - kh-test-rabbitmq

  kh-test-worker:
    image: kinkyharbor/kinkyharbor-backend-worker:latest
    container_name: kh-test-worker
    networks:
      - kh-test-backend
    environment:
      - "CELERY_RABBITMQ_HOST=kh-test-rabbitmq"
      - "MONGO_HOST=kh-test-mongo"
    depends_on:
      - kh-test-rabbitmq

  # =========================
  # =  KINKY HARBOR: DEMO   =
  # =========================
  kh-demo-frontend:
    image: kinkyharbor/kinkyharbor-frontend-nuxt:precompiled-demo
    container_name: kh-demo-frontend
    restart: always
    networks:
      - traefik
    environment:
      - "TZ=${DEFAULT_TIMEZONE}"
      - "DEMO=True"
      - "KH_BASE_URL=https://demo.${DEFAULT_DOMAIN}"
      - "API_URL=https://demo-api.${DEFAULT_DOMAIN}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

  kh-demo-backend:
    image: kinkyharbor/kinkyharbor-backend-fastapi:stable
    container_name: kh-demo-backend
    restart: always
    depends_on:
      - kh-demo-mongo
    networks:
      - traefik
      - kh-demo-backend
    environment:
      - "TZ=${DEFAULT_TIMEZONE}"
      - "FRONTEND_URL=https://demo.${DEFAULT_DOMAIN}"
      - "CORS=[\"https://demo.${DEFAULT_DOMAIN}\"]"
      - "EMAIL_HOSTNAME=${MAIL_HOST}"
      - "EMAIL_PORT=${MAIL_PORT}"
      - "EMAIL_USERNAME=${MAIL_USER}"
      - "EMAIL_PASSWORD=${MAIL_PASS}"
      - "MONGO_HOST=kh-demo-mongo"
      - "CELERY_RABBITMQ_HOST=kh-demo-rabbitmq"
    volumes:
      - "./conf/kh-demo/jwt-keys:/app/jwt-keys"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

  kh-demo-mongo:
    image: mongo
    container_name: kh-demo-mongo
    restart: always
    networks:
      - kh-demo-backend
    environment:
      - "TZ=${DEFAULT_TIMEZONE}"

  kh-demo-rabbitmq:
    container_name: kh-demo-rabbitmq
    image: rabbitmq:3
    networks:
      - kh-demo-backend

  kh-demo-scheduler:
    image: kinkyharbor/kinkyharbor-backend-scheduler:latest
    container_name: kh-demo-scheduler
    networks:
      - kh-demo-backend
    environment:
      - "CELERY_RABBITMQ_HOST=kh-demo-rabbitmq"
    depends_on:
      - kh-demo-rabbitmq

  kh-demo-worker:
    image: kinkyharbor/kinkyharbor-backend-worker:latest
    container_name: kh-demo-worker
    networks:
      - kh-demo-backend
    environment:
      - "CELERY_RABBITMQ_HOST=kh-demo-rabbitmq"
      - "MONGO_HOST=kh-demo-mongo"
    depends_on:
      - kh-demo-rabbitmq

  # =========================
  # =      MAINTENANCE      =
  # =========================
  maintenance:
    image: everydayhero/maintenance:latest
    container_name: maintenance
    restart: always
    networks:
      - traefik
    volumes:
      - "./conf/maintenance:/usr/share/nginx/html"
    environment:
      - "TZ=${DEFAULT_TIMEZONE}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

# #################################################################
# #                            VOLUMES                            #
# #################################################################
volumes:
  traefik-cert:

# #################################################################
# #                            NETWORKS                           #
# #################################################################
networks:
  traefik:
    name: traefik

  kh-test-backend:
    name: kh-test-backend

  kh-demo-backend:
    name: kh-demo-backend
